image: "ruby:2.7.0-alpine"

before_script:
  - apk update && apk add --no-cache build-base mariadb-dev sqlite-dev nodejs npm
  - npm install yarn -g
  - gem install bundler --no-document
  - bundle install


test:unit_test:
  tags: docker
  script:
    - bundle exec rspec spec/unit

test:integration_test:
  tags: docker
  script:
    - yarn add @rails/webpacker
    - bundle exec rspec spec/features
