image: "ruby:2.7"

before_script:
  - apt-get update --qq && apt-get install -y qq build-essentials nodejs yarn
  - ruby -v
  - which ruby
  - gem install bundler --no-document
  - bundle install

unit_test:
  script:
    - bundle exec rspec spec/unit

integration_test:
  script:
    - bundle exec rspec spec/features
