image: "ruby:2.7-alpine"

before_script:
  - apk update && apk add --no-cache nodejs npm
  - npm install yarn -g
  - gem install bundler --no-document
  - bundle install


test:unit_test:
  script:
    - bundle exec rspec spec/unit

test:integration_test:
  script:
    - bundle exec rspec spec/features
