image: "ruby:2.7.0-alpine"

before_script:
  - apk update && apk add --no-cache build-base mariadb-dev sqlite-dev nodejs npm
  - npm install yarn -g
  - gem install bundler --no-document
  - bundle install

stages:
  - unit_test
  - integration_test
  - create_push_image

unit_test:
  stage: unit_test
  tags:
    - docker
  script:
    - bundle exec rspec spec/unit

integration_test:
  stage: integration_test
  tags:
    - docker
  script:
    - yarn add @rails/webpacker
    - rails db:migrate RAILS_ENV=test
    - bundle exec rspec spec/features

# create_push:
#     stage: create_push_image
#     tags:
#       - docker
#     script:
#       - docker login -u=$DOCKER_USER -p=$DOCKER_PASSWORD
#       - IMAGE_TAG=git rev-parse HEAD | cut -c 1-8
#       - docker build -t $DOCKER_USER/$DOCKER_REPO:$IMAGE_TAG .
#       - docker push $DOCKER_USER/$DOCKER_REPO:$IMAGE_TAG
