image: "ruby:2.7"

before_script:
  - apt-get update -qq && apt-get install -y nodejs npm
  - npm install yarn -g
  - yarn install --check-files
  - gem install bundler --no-document
  - bundle install


test:unit_test:
  script:
    - bundle exec rspec spec/unit

test:integration_test:
  script:
    - bundle exec rspec spec/features
