image: "ruby:2.7"

stages:
  - build
  - unit_test
  - integration_test

build:
  stage: build
  script:
    - apt-get update -qq && apt-get install -y nodejs npm
    - npm install yarn -g
    - gem install bundler --no-document
    - bundle install

unit_test:
  stage: unit_test
  script:
    - bundle exec rspec spec/unit
  dependencies:
    - build

integration_test:
  stage: integration_test
  script:
    - bundle exec rspec spec/features
  dependencies:
    - build
