image: "ruby:2.7.0-alpine"

stages:
  - Unit Tests
  - Integration Tests
  - Build and Push Image

Unit Tests:
  stage: Unit Tests
  before_script:
    - apk update && apk add --no-cache build-base mariadb-dev sqlite-dev nodejs npm
    - npm install yarn -g
    - gem install bundler --no-document
    - bundle install
  tags:
    - docker
  script:
    - bundle exec rspec spec/unit

Intergration Tests:
  stage: Integration Tests
  before_script:
    - apk update && apk add --no-cache build-base mariadb-dev sqlite-dev nodejs npm chromium chromium-chromedriver
    - npm install yarn -g
    - gem install bundler --no-document
    - bundle install
    - export CHROMEDRIVER_PATH=/usr/bin/chromedriver
  tags:
    - docker
  script:
    - yarn
    - rails db:migrate RAILS_ENV=test
    - rails webpacker:compile
    - bundle exec rspec spec/features

Build and Push Image:
  stage: Build and Push Image
  image: docker:git
  tags:
    - docker
  only:
    - master
  script:
    - docker login -u=$DOCKER_USER -p=$DOCKER_PASSWORD
    - IMAGE_TAG=$(git rev-parse HEAD | cut -c 1-8)
    - docker build -t $DOCKER_USER/$DOCKER_REPO:$IMAGE_TAG .
    - docker push $DOCKER_USER/$DOCKER_REPO:$IMAGE_TAG
