image: "ruby:2.7"

services:
  - mysql:latest

variables:
  MYSQL_DATABASE: climate_movement_reporting_tool_test
  MYSQL_ROOT_PASSWORD: testdb

before_script:
  - apt-get update -qq && apt-get install -y nodejs npm
  - npm install yarn
  - yarn -v
  - yarn install --check-files
  - ruby -v
  - which ruby
  - gem install bundler --no-document
  - bundle install
  - rake db:create

stages:
  - unit_test
  - integration_test

unit_test:
  stage: unit_test
  script:
    - bundle exec rspec spec/unit

integration_test:
  stage: integration_test
  script:
    - bundle exec rspec spec/features
