version: '3.0'
services:
  db:
    image: mysql:8.0.19
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    expose:
     - 3306
    volumes:
      - dbdata:/var/lib/mysql
  web:
    image:
    environment:
      DATABASE_USERNAME: root
      DATABASE_HOST: db
      RAILS_ENV: # test, development, staging, production
      RAILS_MASTER_KEY: #SECRET KEY IN PASSWORD MANAGER
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db
volumes:
  dbdata:
